env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - google
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - prettier
rules: {
  "react/display-name": "off",
  "require-jsdoc": "off",
  "prettier/prettier": ["error", {
    "endOfLine":"auto"
  }],
}
