import { StyleSheet } from 'react-native';

import * as colors from '../../../theme/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.black,
    justifyContent: 'center',
  },
  mainView: {
    flex: 1,
    paddingTop: 75,
    paddingBottom: 50,
    paddingHorizontal: 50,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  subView: {
    alignItems: 'center',
    width: '100%',
  },
  headerText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 35,
  },
  text: {
    color: colors.red,
    fontWeight: '400',
    fontSize: 25,
  },
  modalText: {
    color: colors.red,
    fontWeight: '400',
    fontSize: 25,
  },
  errorText: {
    color: colors.red3,
    fontWeight: '600',
    fontSize: 18,
  },
  inputBox: {
    width: '100%',
    padding: 15,
    fontSize: 18,
    borderColor: colors.gray0,
    borderBottomWidth: 2,
    textAlign: 'center',
    marginBottom: -15,
  },
  changePasswordInputBox: {
    width: '75%',
    padding: 15,
    fontSize: 15,
    borderColor: colors.gray0,
    borderBottomWidth: 2,
    textAlign: 'center',
    margin: 10,
  },
  defaultProfilePicture: {
    marginTop: 15,
    width: 165,
    height: 165,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    borderRadius: 100,
    backgroundColor: colors.gray2,
  },
  settingsView: {
    marginTop: 30,
    marginBottom: 10,
    marginRight: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  settingText: {
    marginTop: 6,
    fontSize: 16,
    textAlign: 'left',
    marginRight: 200,
    color: colors.white,
  },
  roundButton: {
    marginTop: 15,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    borderRadius: 100,
    backgroundColor: colors.red,
  },
  roundButton2: {
    marginTop: 15,
    width: 35,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    borderRadius: 100,
    backgroundColor: colors.yellow,
  },
  spotifyButton: {
    marginBottom: 5,
    paddingVertical: 20,
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: colors.blue2,
    borderWidth: 1,
    borderRadius: 30,
    width: 200,
    paddingLeft: 20,
    marginTop: 30,
  },
  spotifyButtonText: {
    fontSize: 15,
    color: colors.white,
  },
  spotifyLogo: {
    marginRight: 15,
    width: 20,
    height: 20,
  },
  settingsText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: 20,
    marginTop: 60,
  },
  logoutButton: {
    backgroundColor: colors.blue2,
    width: '100%',
    paddingVertical: 15,
    borderRadius: 50,
    marginBottom: 15,
  },
  logoutButtonText: {
    textAlign: 'center',
    color: colors.white,
    fontWeight: 'bold',
  },
  infoButtonText: {
    textAlign: 'center',
    color: colors.white,
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 10,
  },
  editButton: {
    marginLeft: 285,
    marginTop: -30,
  },
  buttonView: {},
});

export default styles;
